### ISSUE TITLE
Beealyzer improvement

### ISSUE THREAD

**Issue by ProgramCrafter** [ProgramCrafter/lua-utils#1]
- [x] ~~Flags meaning should be made more clear (it may be hard to understand that N means night-working, R - rain tolerance, etc)~~ (user shall read documentation before using the program :smile:);
- [x] ~~Controls must be stated explicitly, maybe in the bottom row (LMB for throwing a bee away, RMB for explicit list refresh, LMB on top row for exitting)~~ (same);
- [x] Princess/drone separation must be thought of (now it's filled and non-filled stars, but it would be better to use crowns);
- [x] Interface should resize itself in order to look better on tier3 screens, as now it uses only 80x25 points;
- [x] Bees should be sorted in order of their "tier";
- [x] Need to find out colours of other bees species, not only listed in the code;
- [x] ~~Need to implement buffering and `gpu.copy` bees information whenever possible~~;
- [x] Add settings like sides of chest and trusted players to use the program;
- [x] Add multi-chest support;
- [ ] Add multi-screen support;
- [ ] Add content scrolling;
- [ ] Check integration with ME networks (Applied Energistics 2).

**Comment by ProgramCrafter** [comment]
Added tier3 terminals support in [94643a7](https://github.com/ProgramCrafter/lua-utils/commit/94643a7ccf44dfec05d6e9f55cd7e00288b8063b).

**Comment by ProgramCrafter** [comment]
Started sorting bees in [a1b5998](https://github.com/ProgramCrafter/lua-utils/commit/a1b59985b84b781799999a291e7431c39234f1ad).

**Comment by ProgramCrafter** [comment]
Sorting respects type of bee (drone/princess), so I think there is no need to separate them further.

**Comment by ProgramCrafter** [comment]
Settings added in [9a732f5](https://github.com/ProgramCrafter/lua-utils/commit/9a732f513ff3639da9e20f992f7d5c61f14e3c49).

**Comment by ProgramCrafter** [comment]
Multi-chest support added in [a22e5e5](https://github.com/ProgramCrafter/lua-utils/commit/a22e5e50ad46f130f6a7ec5959cd7282bb8a06df).

**Comment by ProgramCrafter** [comment]
All bees found out in [74b19af](https://github.com/ProgramCrafter/lua-utils/commit/74b19afe8d5bbae6875fcca684cb01e822fcec9a).
